### ISSUE TITLE
IO pins

### ISSUE THREAD

**Issue by schoeberl** [Edu4Chip/Didactic-SoC#1]
Will we have IO pins multiplexed for the student projects? A handful of pins connected to one or, better yet, two PMODs would be usable, e.g., to provide external memory (Flash, SRAM) for a project.

**Comment by Kyrhe** [comment]
Each student project has been granted 8 x GPIOs that will be eventually mapped to 2 x PMOD connectors on PCB. Marking it here as well as having discussed in the regular meeting.
