### ISSUE TITLE
Address used in ss0_test

### ISSUE THREAD

**Issue by SyedAnasAlam** [Edu4Chip/Didactic-SoC#4]
In https://github.com/Edu4Chip/Didactic-SoC/blob/main/sw/ss0_test/ss0_test.c
The address has an extra 0. The address should be 0x01050000

**Comment by Kyrhe** [comment]
Thanks for catching this, fixed by [Commit 6384f86
](https://github.com/Edu4Chip/Didactic-SoC/commit/6384f86a7411dcbf30d06dc45dba80bfe83569da)
